stages:
    
    run:
            
        echo "## Model run" > report.md

                          # main code to run
        python code/concat_and_plot.py >> report.md


                        # Results
        echo "## Model plots" >> report.md

                        # plotting in md each of the listed figures:
      foreach: ${filenames}$
        do:
            cml-publish ${item.prop1} --md --title ${key} >> report.md
          
        cml-send-comment report.md