name: plot-IBGE-spatial-dataset

on: [push]

jobs:
    deploy-cloud-runner:
        runs-on: [ubuntu-latest]
        container: docker://dvcorg/cml:latest

        steps:
          - uses: actions/setup-python@v2
            with:
              python-version: '3.8.x'


          - name: deploy
            shell: bash

            env:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
                                         #GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
                                         #GDRIVE_SECRET_ACCESS_KEY: ${{secrets.GDRIVE_ACCESS_TOKEN}}

            run: |

              echo "\n\n\t\tDeploying... \n\n\n\n"    

              MACHINE="cml$(date +%s)"

              pip install -r requirements.txt
              
                             # Pull data & run-cache from Drive
                                    # dvc pull data
                                    # dvc repro
              
              python concat_and_plot.py | echo # | tee logfile.log
              
              cml-publish results/figure/Domicilio_V147.png --md --title 'spatial Domicilio V147' >> report.md
              
              cml-send-comment report.md
              
              
            