name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: iterative/setup-cml@v1

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
                         # Pull data & run-cache from S3 and reproduce pipeline
          dvc pull data --run-cache
          dvc repro
          
          pip3 install -r requirements.txt
          python concat_and_plot.py
          
          cml-publish results/figure/Domicilio_V147.png --md --title 'spatial Domicilio V147' >> report.md
          cml-send-comment report.md
        