name: plot-IBGE-spatial-dataset

on: [push]


jobs:
    deploy-cloud-runner:
        runs-on: [ubuntu-latest]
        container: docker://dvcorg/cml-py3:latest

        steps:
          - uses: actions/checkout@v2
            

          - name: cml_run
            shell: bash

            env:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              
                                          # GDRIVE_CREDENTIALS_DATA: ''

            
               
            run: |
                  
                  
                  echo "## Model run" > report.md
                  
                  pip install -r requirements.txt
                  
                  
                  # Pull data & run-cache from google Drive and reproduce pipeline
                  # dvc pull data #  --run-cache
                  # dvc repro
                  
                  # main code to run
                  python code/concat_and_plot.py >> report.md
                  
                  
                  # Results
                  echo "## Model plots" >> report.md
                  
                  # plotting in md each of the listed figures:
                  foreach: ${cml_base_case/code/list_of_plots.filenames}$
                      do:
                        cml-publish ${item.prop1} --md --title ${key} >> report.md
                      
                  cml-send-comment report.md